title: Old school
author: Evgeny Mushtatov
theme: minima
email: mushtatov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my test blog was created using Jekyll on GitHub.

# social links
github_username:  emushtat # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
